<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:anykgw2="http://tarhely.gov.hu/anykgw2" name="AuthTokenService"
                  targetNamespace="http://tarhely.gov.hu/anykgw2">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:anykgw2="http://tarhely.gov.hu/anykgw2"
                   version="1.0">

            <xs:import namespace="http://tarhely.gov.hu/anykgw2" schemaLocation="anykgw2.xsd"/>

        </xs:schema>
    </wsdl:types>
    <wsdl:message name="AuthTokenRequest">
        <wsdl:part element="anykgw2:AuthTokenRequest" name="authTokenRequest">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="AuthTokenResponse">
        <wsdl:part element="anykgw2:AuthTokenResponse" name="authTokenResponse">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="AuthTokenService">
        <wsdl:operation name="GetAuthToken">
            <wsdl:input message="anykgw2:AuthTokenRequest" name="AuthTokenRequest">
            </wsdl:input>
            <wsdl:output message="anykgw2:AuthTokenResponse" name="AuthTokenResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AuthTokenServiceSoapBinding" type="anykgw2:AuthTokenService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetAuthToken">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="AuthTokenRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AuthTokenResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AuthTokenService">
        <wsdl:port binding="anykgw2:AuthTokenServiceSoapBinding" name="AuthTokenServicePort">
            <soap:address location="https://teszt-krwsfe.magyarorszag.hu/anykgw2/AuthTokenService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>